# Generated by Django 4.2.11 on 2024-06-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0072_merge_20240325_1609"),
    ]

    operations = [
        migrations.CreateModel(
            name="Freightcomv2Settings",
            fields=[
                (
                    "carrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="providers.carrier",
                    ),
                ),
                ("apiKey", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Freightcomv2 Settings",
                "verbose_name_plural": "Freightcomv2 Settings",
                "db_table": "freightcomv2-settings",
            },
            bases=("providers.carrier",),
        ),
    ]
